orders/urls.py
from django.urls import path, re_path

from django.conf.urls import url

from . import views

app_name = 'orders'
#list of urls supported by this app (orders)
urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register_view, name="register"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path('add-to-cart/<int:item_id>', views.add_to_cart, name="add_to_cart"),
    path('customize_order/str<food>', views.customize_order, name="customize_order"),
    path('ordersummary/', views.order_details, name="ordersummary"),
    path('success/', views.success, name='success'),
    path('item/delete/<item_id>)/', views.delete_from_cart, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('updaterecords/<int:order_id>', views.updaterecords, name='updaterecords'), # redirects to the update
    path('profile', views.profile, name='profile'),
    path('allorders', views.allorders, name='allorders')

]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views as auth_views



urlpatterns = [
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    #path('login/', auth_views.LoginView.as_view())
]

orders/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
User = get_user_model()


# Create your models here.
#you can also run python manage.py check; this checks for any problems in
#your project without making migrations or touching the database.



class Menu_Item(models.Model):

    MENU_CATEGORIES = (
    ('Pizza', 'Pizza'),
    ('Pasta', 'Pasta'),
    ('Subs', 'Subs'),
    ('Salad', 'Salad'),
    ('Dinner_Platter', 'Dinner_Platter'),
    ('Topping', 'Topping'),
    ('Extra', 'Extra'),
    ('Dessert', 'Dessert'),
    ('Pastry', 'Pastry'),
    ('Main', 'Main'),
    ('Appetizer', 'Appetizer'),
    ('Side', 'Side'),
    ('Miscellaneous', 'Miscellaneous')
    )

    SIZE_CATEGORIES = (
    ('Sm', 'Small'),
    ('Md', 'Medium'),
    ('Lg', 'Large'),
    ('XL', 'Extra_Large')
    )

    #get rid of choices.

    #can get rid of the choices if someone wanted to add more categories
    category = models.CharField(max_length=36, null=True, blank=True,
                                choices=MENU_CATEGORIES,
                                help_text='Enter the category of the menu item')

    name = models.CharField(max_length=128,
                            help_text='Enter name of the menu item')

    price =  models.DecimalField(max_digits=4, null=True, blank=True,
                                decimal_places=2, default=0.00)

    sizes = models.CharField(max_length=4, null=True, blank=True,
                                choices=SIZE_CATEGORIES,
                                help_text='Enter the allowable sizes \
                                            of the menu item')

    toppings = models.CharField( max_length=400, blank=True, null=True,
                                help_text='Enter toppings')

    num_toppings = models.CharField(max_length=10, blank=True, null=True)


    def __str__(self):
        return f" Category:{self.category} - Name:{self.name} - \
        Sizes:{self.sizes} - Price: {self.price} \
        -numtoppings {self.num_toppings} - toppings {self.toppings}"





class Topping(models.Model):

    topping_name = models.CharField(max_length=36)

    price = models.DecimalField(max_digits=4, null=True, blank=True,
                                decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.topping_name}"

class Extras(models.Model):
    name = models.CharField(max_length=64, help_text='Enter name of the extra')

    price = models.DecimalField(max_digits=4,decimal_places=2,
                        default=0, help_text='Enter price of the extra')

    def __str__(self):
        return f"{self.name} - {self.price}"



# use my custom user model and save when user is created.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)

    menu_items = models.ManyToManyField(Menu_Item, blank=True)


    def __str__(self):
        return f"{self.user.username}"


def post_save_profile_create(sender, instance, created, *args, **kwargs):
    if created:
        user_profile, created = Profile.objects.get_or_create(user=instance)

post_save.connect(post_save_profile_create, sender=settings.AUTH_USER_MODEL)

class OrderItem(models.Model):
    menu_item = models.ForeignKey(Menu_Item,on_delete=models.CASCADE,
                                    blank=True, null=True)

    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    is_topping =models.BooleanField(default=False)
    num_extras = models.IntegerField( blank=True, default=0)
    extras = models.CharField(max_length=400,  blank=True, null=True)
    extras_cost = models.DecimalField(max_digits=4,decimal_places=2, default = 0.00)
    ptoppings = models.CharField(max_length=400,  blank=True, null=True)
    def __str__(self):
            return f"Menu-Item: {self.menu_item} - \
                Toppings: {self.ptoppings}\
                - Num extras:{self.num_extras} \
                - sub_extras {self.extras} \
                status:{self.is_ordered} \
                Date ordered: {self.date_added} - \
            "


class Order(models.Model):
    ref_code = models.CharField(max_length=15, blank=True)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    ordered_items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    # reutrn number of ordered items.
    def num_order_items(self):
        return self.order_items.count()

    #get all the orders ordered_items
    def get_cart_ordered_items(self):
        return self.ordered_items.all()
        #exclude(is_topping=True)

    def get_cart_ordered_items_toppings(self):
        return self.ordered_items.all()
        #sum of total price of all ordered_items

    def get_cart_total(self):

    #    Extra = Menu_Item.objects.filter(name="Sub_Extra")

        return sum([item.menu_item.price for item in self.ordered_items.all()]
        + [item.extras_cost for item in self.ordered_items.all()])
        #.exclude(is_topping=True)])


    def __str__(self):
        return f" User: {self.owner} ---- \
        Date ordered; {self.date_ordered}----\n \
        Order Complete Status: {self.is_ordered}---- \n \
        Total Price: {self.get_cart_total()} ---- \n \
        Ordered Items:{self.ordered_items.all()} -- \
        "

orders/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib import messages

from .models import (Topping, Menu_Item, Profile,
Extras, Order, OrderItem,  User, )

import datetime

# Create your views here.

""" user profile view"""
@login_required()
def profile(request):

    my_user_profile = Profile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)


    context = { 'my_orders': my_orders, 'user': request.user}

    return render(request, "orders/profile.html", context)

""" view for all orders summary"""
def allorders(request):

    profiles = Profile.objects.all()
    all_orders = Order.objects.filter(is_ordered=True)

    context = { 'all_orders': all_orders}

    return render(request, "orders/allorders.html", context)

""" menu view """
@login_required()
def index(request):

    if not request.user.is_authenticated:
        return render(request, "orders/login.html", {"message": None})

    #get all items on menu except toppings and extras
    menu_items = Menu_Item.objects.exclude(category__icontains="Topping") \
    .exclude(category__icontains="Extra")


    #get the ordered items so far
    filtered_orders = Order.objects.filter(owner=request.user.profile,
                                          is_ordered=False)
    current_order_products = []

    item_count = 0

    # if there is any currently ordered items put them in current odered prodects
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.ordered_items.all()
        current_order_products = [menu_item.menu_item for menu_item
                                in user_order_items]

        #get number of items in cart
        item_count = user_order.ordered_items.count()

    context ={

        'current_order_products': current_order_products,
        'item_count': item_count,
        "user": request.user,
        "menu_item": menu_items.order_by('-category')
    }
    return render(request, "orders/index.html", context)

@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id

    #get the menuitem by id  passed through kwargs
    menu_item = Menu_Item.objects.filter(id=kwargs.get('item_id', "")).first() #item id sent from the url

    # get quanitity ordered
    quantity = int(request.POST['quantity'])

    # create orderItem of the selected menu_item X qunatity

    for x in range(quantity):
        order_item = OrderItem.objects.create(menu_item=menu_item)
    # create order associated with the user
        user_order, status = Order.objects.get_or_create(owner=user_profile,
                                                        is_ordered=False)

        user_order.ordered_items.add(order_item)

    if status:
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, f" {quantity} {menu_item.sizes} \
                            {menu_item.name} added to cart")

    return HttpResponseRedirect(reverse('orders:index'))

""" view for customizing pizza and subs and anything customizable """
@login_required()
def customize_order(request, food, *args,**kwargs):

    if request.method == "GET":


        toppings = Menu_Item.objects.filter(category__contains="Topping")

        extras = Extras.objects.all()

        extra_cheese=Extras.objects.filter(name__icontains="cheese")

        menu_items = Menu_Item.objects.all()

        ordered_item = Menu_Item.objects.filter(name=food).first()

        context ={

                "ordered_item": ordered_item,
                "user": request.user,
                "menu_item": menu_items,
                "toppings": toppings,
                "extras": extras,
                'extra_cheese': extra_cheese

            }
        return render(request, "orders/customize_order.html", context)


    """ if method is POST """
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id

    menu_item = Menu_Item.objects.filter(name=food).first()
    print (f"this is menu item in get {menu_item}")


    #get toppings depening on number of toppings from form
    toppings = []

    if "Special" in food:
        special_toppings = request.POST.getlist('special_toppings')
        print(f"special_toppings:{special_toppings} \n")
        toppings = special_toppings

        if len(toppings) < 4:

            messages.info(request, "You chose less than 3 toppings! \
             A special pizza needs \
            4 or more toppings! ")
            # get all menu items
            menu_items = Menu_Item.objects.all()
            toppings = Menu_Item.objects.filter(category__contains="Topping")
            menu_items = Menu_Item.objects.all()
            ordered_item = Menu_Item.objects.filter(name=food).first()

            context ={

                    "ordered_item": ordered_item,
                    "user": request.user,
                    "menu_item": menu_items,
                    "toppings": toppings,

                }
            return render(request, "orders/customize_order.html", context)



    if "Special" not in food and "Pizza" in food:
        topping1 = request.POST["topping1"]
        toppings.append(topping1)

        try:
            topping2 = request.POST["topping2"]
            toppings.append(topping2)
        except MultiValueDictKeyError:
            toppings2 = False

        try:
            topping3 = request.POST["topping3"]
            toppings.append(topping3)

        except MultiValueDictKeyError:
            topping3 = False

    # get the extras
    extras = []

    num_extras = 0

    if menu_item.category == "Subs":
        sub_extras = request.POST.getlist('sub_extras')
        #print(f"sub_extras:{sub_extras} \n")

        for extra in sub_extras:
            extras.append(extra + "+ .50c")
            num_extras += 1

    #using price of sub_extra to get the price of extras

    sub_extra = Menu_Item.objects.get(name="Sub_Extra")

    extra_price = sub_extra.price
    #calculate extra cost for extras
    extras_cost = num_extras * extra_price

    #establish quantity of items ordered
    quantity = int(request.POST['quantity'])
    #print(f"custom quantity:{quantity} \n")

    # create orderItem of the selected menu_item\
    for x in range(quantity):
        #order_item = OrderItem.objects.create(menu_item=menu_item)
        order_item = OrderItem.objects.create(menu_item=menu_item,
        ptoppings=toppings, extras=extras, num_extras=num_extras,
        extras_cost=extras_cost )


        # create order associated with the user
        user_order, status = Order.objects.get_or_create(owner=user_profile,
                                                        is_ordered=False)

        user_order.ordered_items.add(order_item)

    if status:
        user_order.save()

    messages.info(request, f" {quantity} {menu_item.sizes} {menu_item.name} \
                            added to cart")

    return HttpResponseRedirect(reverse('orders:index'))


""" view for deleting items from cart """
@login_required()
def delete_from_cart(request, item_id):

    #get ordered item by id
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    deleted_item = OrderItem.objects.get(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, f" {deleted_item.menu_item.sizes} \
            {deleted_item.menu_item.name}  removed from cart")

    return redirect(reverse('orders:ordersummary'))


""" seperate function for getting the cart for summary and checkout """
@login_required()
def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders with is_ordered = false
        return order[0]
    return 0

""" view for showing the cart with current items """
@login_required()
def order_details(request, **kwargs):

    existing_order = get_user_pending_order(request)
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)

    context = {
        'order': existing_order,
        #'orders': orders
    }
    return render(request, 'orders/ordersummary.html', context)


""" view for confirming current order and checking out """
@login_required()
def checkout(request, **kwargs):
    existing_order = get_user_pending_order(request)

    context = {
        'order': existing_order,
    }

    return render(request, 'orders/checkout.html', context)

""" this view save updates the orders from pending to ordered """
@login_required()
def updaterecords(request, order_id):
    # get the order being processed
    order_to_purchase = Order.objects.filter(pk=order_id).first()

    # update each of the individual ordered_items
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()


    # get all ordered_items in the order and update the entire order
    order_items = order_to_purchase.ordered_items.all()

    # update order- is ordered to true
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)

orders/templates/orders/checkout.html
{% extends "orders/base.html" %}

{% block title %} check out {% endblock %}
{% block body %}
{% load static %}



<body>

  <div class="my-menu-flex-container">

    <table class="table-dark  text-center table-bordered table-hover " style="margin-top:10%; width:100%">
      <tr>
        <td colspan="2">
          <h4>Check Out. </h4>

          <h6> Please confirm order details</h6>
        </td>
      </tr>
      <tr>
        <td>
          {% for item in order.get_cart_ordered_items %}
      <tr>

        {%if item.menu_item.category == "Pizza" and "Topping" in item.menu_item.name %}
        {% if item.ptoppings %}
        <td>
          {{item.menu_item.sizes}}
          {{ item.menu_item.name }}

          Toppings: {{ item.ptoppings }}


        </td>
        {% endif %}
        {% endif %}


        {%if item.menu_item.category == "Pizza" and "Topping" not in item.menu_item.name %}
        <td>
          {{item.menu_item.sizes}}
          {{ item.menu_item.name }}
        </td>
        {% endif %}



        <!-- subs with no extras -->

        {% if item.menu_item.category == "Subs" and item.num_extras == 0 %}

        <td>
          {{item.menu_item.sizes}}

          {{ item.menu_item.name }}

        </td>

        {% endif %}


        {% if item.num_extras > 0 %}
        <td>
          {{item.menu_item.sizes}}
          {{ item.menu_item.name }}
          Extras: {{ item.extras }}
        </td>
        {% endif %}

        {% if item.menu_item.category != "Pizza" and item.menu_item.category != "Subs" %}
        <td>
          {% if item.menu_item.sizes%}
          {{item.menu_item.sizes}}
          {% endif %}

          {{ item.menu_item.name }}
        </td>
        {% endif %}

        {% if item.num_extras > 0 %}
        <td>{{ item.menu_item.price }}
          + {{item.extras_cost}}</td>
        {%else%}
        <td>${{ item.menu_item.price }}</td>

        {%endif%}
      </tr>
      {% endfor %}

      <tr>
        <td><strong>Order Total</strong> </td>
        <td> <strong>${{ order.get_cart_total }}</strong></td>


      </tr>

      <tr>
        <td></td>
        <td> <a <button type="submit" href="{% url 'orders:updaterecords' order.id %}" class="pull-right btn btn-primary">Checkout</button> </a>
        </td>
      </tr>
    </table>
    <!-- <form action="process_payment" method="post" id="payment-form""> -->


    <!-- </form> -->

  </div>

{% endblock %}



</body>
</html>

orders/templates/orders/index.html
{% extends "orders/base.html" %}



{% block title %} Menu{% endblock %}


{% load static %}




{% block body %}

<link rel="stylesheet" type="text/css" href="{% static 'orders/index.css' %}">

   <nav class="navbar navbar-expand-lg bg-dark navbar-dark justify-content-center fixed-top">
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav"
     aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbar-nav">

     <ul class="navbar-nav mr-auto">

         <li class="nav-item">

           <a class="nav-link active" href="#Pizza">Pizza</a>

         </li>

        <li class="nav-item">

          <a class="nav-link" href="#Pasta">Pasta</a>

        </li>

        <li class="nav-item">

          <a class="nav-link" href="#Salad">Salad</a>

        </li>

        <li class="nav-item">
          <a class="nav-link" href="#Subs">Subs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#Dinner_Platter">Dinner Platters</a>
        </li>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Menu</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href= "login">login</a>
            <a class="dropdown-item" href="logout">logout</a>
            <a class="dropdown-item" href="register">register</a>
            <a class="dropdown-item" href="profile">Profile</a>
            {% if request.user.is_superuser %}
             <a class="dropdown-item" href="/admin">Admin</a>
            <a class="dropdown-item" href="/allorders">All Orders</a>

             {% endif %}
          </div>
        </li>

      </ul>
      <span class="nav-item">
        <div class="" style="color: white">
          Welcome, {{ user.username }}

       </div>
      </span>

          {% if current_order_products != NONE %}
           <span class=" ">

            <a class="nav-link text-light mr-auto" href="{% url 'orders:ordersummary' %}"><img src="/static/orders/img/cart.png" width="35px" height="30px"  >{{item_count}}</a>

          </span>
          {% endif %}
      </div>
    </nav>




        <div class="my-menu-flex-container">


          {% if messages %}
          {% for message in messages %}
          <div class= "alert alert-info" role="alert" style="margin-top: 3%">
                  {{ message }}
          </div>
          {% endfor %}
          {% endif %}

          <table  class="table-dark table-sm  table-responsive-sm text-center
          table-bordered table-hover" style="width:100%; margin-top: 3%">
            <thead class="thead-dark">


              <tr class="bg-primary">
                      <th colspan="5"><h1>OUR MENU</h1></th>
              </tr>
              <tr>

                <th scope="col">Item</th>
                <th scope="col">Size</th>
                <th scope="col">Price</th>



                {% if current_order_products %}
                <th><a href="{% url 'orders:ordersummary' %}"
                  class="btn btn-info">Go to Cart</a>

                  {% if item_count %}

                # Items in Cart: {{item_count}} </th>

                {% endif %}

                {% else %}
                <th>No items in cart</th>
                {%endif%}
              </tr>
            </thead>
            <tbody>



              {% for item in menu_item %}



        <!-- <form class="" action="{% url 'orders:add_to_cart' item.id %}" method="post"> -->

             {% csrf_token %}

              {% ifchanged item.category %}


              <tr class="table-info text-dark" id="{{item.category}}">

                <th scope="row" colspan="5"  > <h2> {{ item.category }} </h2> </th>


             </tr> {% endifchanged %}

              <tr>

                <td>{{item.name}}</td>
                <td>{{item.sizes}}</td>
                <td>{{item.price}}</td>



              {% if item.category == "Pizza" and "Topping" in item.name %}


              <td><a href="{% url 'orders:customize_order' item.name %}" class="btn btn-info">Customize</a></td>

              {% elif item.category == "Subs" %}
              <td><a href="{% url 'orders:customize_order' item.name %}" class="btn btn-info">Customize</a></td>
            {% else %}
              <form class="" action="{% url 'orders:add_to_cart' item.id %}" method="post">
                      {% csrf_token %}

              <td>
                <label for="quantity">Quantity:</label>
                <input name="quantity" id="quantity" type="number" value=1 min=1 max=30 >
              <button type="submit" class="btn btn-warning">Add to Cart</button></td>
                </form>
              <!-- <td><a href="{% url 'orders:add_to_cart' item.id %}" class="btn btn-warning">Add to Cart</a></td> -->
            {%endif%}
              <!-- <td><input type="submit" value="Add to Cart" class="btn btn-warning"></td> -->

               <!-- <td><button type="submit"><a href="{% url 'orders:add_to_cart' item.id %}" class="btn btn-warning">Add to Cart</a></button></td> -->


              </tr>
              {% endfor %}

            </tbody>

          </table>

          <br>
        </div>

{% endblock %}

orders/templates/orders/login.html
{% extends "orders/base.html" %}

{% block title %}
Login
{% endblock %}


{% block body %}



<div class="container-login">


  <div class="row justify-content-center ">


    <div class="col mt-3 p-3" style="color:lightblue">

      <div>

        {% if message %}
        <div>
          <h3 style="color:lightblue"> {{ message }} </h3>
        </div>
        {% endif %}

        <h1>Welcome to Pizza Hut!</h1>
        <h3> Login</h3>

      </div>


      <form class="form-conrtol" action="{% url 'orders:login' %}" method="post">
        {% csrf_token %}

        <!-- <div class="form-row">
      <div class="form-col"  <div class="form-group">> -->

        <div class="form-group">

          <label for="username">Username</label>
          <input class="form-control" id="username" placeholder="username" name="username" type="text" />
        </div>

        <div class="form-group">
          <label for="password">Password</label>

          <input class="form-control" id="password" placeholder="password" name="password" type="password" />

        </div>

        <div class="row justify-content-center">

          <input class="btn btn-primary mr-1" type="submit" value="Login">
      </form>

      <a href="{% url 'orders:register' %}" class="btn btn-info">Register</a>

    </div>


  </div>



</div>

{% endblock %}

orders/templates/orders/ordersummary.html
{% extends "orders/base.html" %}

{% block title %} Order Summary {% endblock %}
{% block body %}
{% load static %}



<div class="my-menu-flex-container">
  <!-- <h1 style="color:white">Cart</h1> -->
  <table class=" table-dark table-sm table-responsive-sm text-center table-bordered table-hover" style="margin-top:5%; width:100%  ">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert" style="margin-top: 3%">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}


    <tr class="bg-primary">
      <th colspan="4">
        <h1>Cart</h1>
      </th>
    </tr>

    <tr>
      <th>No.</th>
      <th>Item</th>
      <th>Price</th>

    </tr>
    {% for item in order.get_cart_ordered_items %}
    <tr>
      <td>{{ forloop.counter }}</td>


      <!-- pizza with toppings -->
      {%if item.menu_item.category == "Pizza" and "Topping" in item.menu_item.name %}

      {% if item.ptoppings != False %}
      <td>
        {{item.menu_item.sizes}}
        {{ item.menu_item.name }}
        Toppings: {{ item.ptoppings }}

      </td>
      {% endif %}

      {% endif %}



      <!-- regular pizza with no toppings -->
      {%if item.menu_item.category == "Pizza" and "Topping" not in item.menu_item.name %}
      <td>
        {{item.menu_item.sizes}}
        {{ item.menu_item.name }}

      </td>
      {% endif %}


      <!-- subs with no extras -->

      {% if item.menu_item.category == "Subs" and item.num_extras == 0 %}

      <td>
        {{item.menu_item.sizes}}

        {{ item.menu_item.name }}

      </td>

      {% endif %}


      <!-- subs with extras -->

      {% if item.num_extras > 0 %}
      <td>
        {{item.menu_item.sizes}}

        {{ item.menu_item.name }}
        Extras: {{ item.extras }}


      </td>

      {% endif %}

      <!--any menu item not a pizza or sub -->

      {% if item.menu_item.category != "Pizza" and item.menu_item.category != "Subs" %}

      <td>
        {% if item.menu_item.sizes%}
        {{item.menu_item.sizes}}
        {% endif %}
        {{ item.menu_item.name }}

      </td>

      {% endif %}

      <!-- subs with extras and price for extras -->

      {% if item.num_extras > 0 %}
      <td>
        {{ item.menu_item.price }} + {{item.extras_cost}} </td>

      {% else %}

      <!-- price for everything not a sub -->

      <td> {{item.menu_item.price}} </td>
      {% endif %}


      <td>

        <a href="{% url 'orders:delete_item' item.id %}" class="btn btn-sm btn-warning">Remove</a>


      </td>


      {% empty %}
    <tr>
      <td colspan=3> You have not added any items yet.</td>
    </tr>
    {% endfor %}
    <tr>
      {% if order.get_cart_total != None %}
      <td colspan=2>
        <strong class="pull-right">Order Total:</strong>
      </td>

      <td colspan=1>
        $<strong>{{ order.get_cart_total}}</strong>
      </td>
      {% endif %}
    </tr>
    <tr>

      <td colspan=3>
        <a href="{% url 'orders:index' %}" class="btn btn-warning ">
          {% if order %}Return to Menu{% else %}Add Items to Cart {% endif %}
        </a>
      </td>
      <td colspan=5>
        {% if order.get_cart_ordered_items %}
        <a href="{% url 'orders:checkout' %}" class=" btn btn-sm btn-primary">Checkout</a>
        {% endif %}
      </td>
    </tr>
  </table>

</div>

{% endblock %}

orders/templates/orders/register.html
{% extends "orders/base.html" %}

{% block title %}
Register
{% endblock %}
{% block body %}


<div class="container-login ">
  <div class="row justify-content-center">
        <div class="col-12 mt-3 p-3 " style="color:lightblue">
          <div >

    {% if message %}
    <div class='text-center alert alert-info'>
      <h3 style="color:red"> {{message}} </h3>
    </div>
    {% endif %}
    </div>
    <h1>Sign up with your email address.</h1>

    <form  action="{% url 'orders:register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control"
            id="username" placeholder="Username" name="username">
        </div>

        <div class="form-group">
            <label for="email">Email address:</label>
            <input type="email" class="form-control"
            id="email" placeholder="Email Address" name="email">
        </div>

        <div class="form-group">
            <label for="first_name">First name:</label>
            <input type="text" class="form-control"
            id="first_name" placeholder="First Name" name="first_name">
        </div>

        <div class="form-group">
            <label for="last_name">Last name:</label>
            <input type="text" class="form-control"
            id="last_name" placeholder="Last Name" name="last_name">
        </div>

        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" class="form-control" autocomplete="false"
            id="password" placeholder="Password" name="password">
        </div>

        <div class="form-group">
            <label for="confirm_password">Retype Password:</label>
            <input type="password" class="form-control"
            id="confirm_password" placeholder="Password" name="confirm_password">
        </div>
        <input type="submit" class="btn btn-primary" value="Register">
    </form>
</div>
</div>
  </div>

{% endblock %}